### PR TITLE
Added recipe for openssl-1.0.0q

### PR DESCRIPTION
**Pull request by jdmundrawala**

### CODE REVIEW

**Comment by Azolo** [comment]
Awesome! Thank you

**Comment by Azolo** [comment]
Binaries are published:
https://bintray.com/oneclick/OpenKnapsack/openssl/1.0.0q/

**Comment by jdmundrawala** [comment]
Awesome... thanks for the being so responsive

**Comment by Azolo** [comment]
Haha. You caught me at the end of a RubyInstaller release.

I was already in the rhythm.

**Pull request merged**
