### PR TITLE
Add openssl 1.0.1m

### PR DESCRIPTION
**Pull request by jaym**

### CODE REVIEW

**Comment by Azolo** [comment]
Hey thanks.

I'm swamped at the moment. I'll try to get to it tonight, but it may be a couple days before I can test, merge, build and upload this.

If you need it quickly, let me know otherwise I'm going to let it slide as something I don't have to worry about at the moment. :grinning:

**Comment by jdmundrawala** [comment]
No rush, I've already got myself a build :)

**Comment by Azolo** [comment]
Wow, I'm seriously sorry. I totally forgot about this. I'll get it built, tested, merged, and uploaded tonight.

**Comment by jaym** [comment]
No problem, might be good to do 1.0.1p instead: https://github.com/jaym/windows-openssl-build/blob/master/knap-build/recipes/openssl/openssl-1.0.1p.knapfile

**Pull request merged**
